language: go

go:
  - 1.6.1
  - tip
  
matrix:
  allow_failures:
    - go: tip
    
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
    
after_success:
  - bash <(curl -s https://codecov.io/bash)
